version: '3.8'

networks:
  test-network:
    driver: bridge
    name: selenium-network

volumes:
  kiwi_db_data:
    driver: local
  kiwi_uploads:
    driver: local

services:
  db:
    image: mariadb:10.6
    container_name: kiwi_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "root_password"
      MARIADB_USER: "kiwi"
      MARIADB_PASSWORD: "kiwi"
      MARIADB_DATABASE: "kiwitcms"
    networks:
      - test-network
    volumes:
      - kiwi_db_data:/var/lib/mysql

  kiwi:
    image: kiwitcms/kiwi:latest
    container_name: kiwi_web
    depends_on:
      - db
    restart: unless-stopped
    environment:
      KIWI_DB_HOST: db
      KIWI_DB_PORT: 3306
      KIWI_DB_NAME: kiwitcms
      KIWI_DB_USER: kiwi
      KIWI_DB_PASSWORD: kiwi
      # SITE_DOMAIN: "my-kiwi-instance.local"
    volumes:
      # Persists uploaded files (screenshots, attachments, etc.)
      - kiwi_uploads:/Kiwi/uploads
    networks:
      - test-network
    ports:
      - "8080:8080"
      - "8443:8443"

  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    networks:
    - test-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config:/etc/selenoid:ro"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/video
      - OVERRIDE_LOG_OUTPUT_DIR=${PWD}/logs
      - TZ=America/Sao_Paulo
      - CONTAINERS_NETWORK=selenium-network
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video",
      "-log-output-dir", "/opt/selenoid/logs",
      "-container-network", "selenium-network",
      "-limit", "8"
    ]
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "4444"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8888:8081"
    environment:
      - DOZZLE_ADDR=:8081
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 60s
      retries: 5
      start_period: 30s

  chrome-puller:
    image: docker:latest
    command: docker pull selenoid/vnc_chrome:128.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - test-network

  video-recorder-puller:
    image: docker:latest
    command: docker pull selenoid/video-recorder:latest-release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - test-network

  run_tests:
      build:
        context: ../
        dockerfile: page_objects_model_selenium/Dockerfile
      volumes:
        - ../page_objects_model_selenium:/app
        - ../page_objects_model_selenium/reports/screenshots:/app/reports/screenshots
        - ../page_objects_model_selenium/reports/allure-results:/app/reports/allure-results
        - ../page_objects_model_selenium/reports/videos:/app/reports/videos
      working_dir: /app
      environment:
        - VIDEO_RECORDING_ENABLED=true
        - SELENIUM_URL=http://selenoid:4444
      networks:
        - test-network
      depends_on:
        - web
        - selenoid
        - faker

  web:
    build:
      context: ../autenticator/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],host.docker.internal,web
    networks:
      - test-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure-api
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "true"
      KEEP_HISTORY_LATEST: 20
      CLEAN_RESULTS_DIRECTORY: "false"
      REMOVE_REPORT_VIDEO_WHEN_MERGED: "false"
    ports:
      - "5050:5050"
    volumes:
      - ../page_objects_model_selenium/reports/allure-results:/app/allure-results
      - ../page_objects_model_selenium/reports/allure-reports:/app/default-reports
    networks:
      - test-network

  allure-ui:
    image: frankescobar/allure-docker-service-ui
    container_name: allure-ui
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    depends_on:
      - allure
    networks:
      - test-network

  faker:
    build:
      context: .
      dockerfile: Dockerfile.faker
    ports:
      - "5000:5000"
    volumes:
      - ./faker:/app/faker
    environment:
      - PORT=5000
    networks:
      - test-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
